### PR TITLE
Fix computer firing on same coord where it had missed before fixes #17

### LINKED ISSUE #17: Computer and AI are able to fire successfully at same sell
When the computer is taking it's turn. It is shooting at the same cell it already missed.

Proposed fixes: 
- Using our fire_upon method in cell to check the cell for fired upon status?
- We may need to change some actual game functions along with this.

### PR DESCRIPTION
**Pull request by JustinD85**
I looked over the game file and believe I isolated the problem and addressed it.

### CODE REVIEW

File: lib/game.rb [hunk 1]
```diff
@@ -78,13 +77,12 @@ def attempt_fire_on_player_ship
     valid_range = @player_board.cells.keys
     valid_range.shuffle!
     coord = valid_range.shift
-    until !@player_board.cells[valid_range.first].fired_upon?
-      coord = valid_range.shift
-      valid_range.shuffle!
+    until !@player_board.cells[coord].fired_upon?
```
Comment (JustinD85) [inline lib/game.rb:80]: We may still have too much logic here, but the issue was we were not using the new coord to validate if we could shoot or not.
