### PR TITLE
Fix prompt not showing player selected same coord

### LINKED ISSUE #25: User not getting prompt if shooting on same cell.

### PR DESCRIPTION
**Pull request by JustinD85**
closes #25

### CODE REVIEW

File: lib/game.rb [hunk 1]
```diff
@@ -80,32 +78,30 @@ def attempt_fire_on_player_ship
...
 
   def attempt_fire_on_computer_ship
     coord = gets.chomp.upcase
 
     until @player.fire_upon?(@computer, coord)
-      coord = gets.chomp.upcase
-      
-      if !@computer.already_shot_at_location?(coord)
+
+      if @computer.already_shot_at_location?(coord)
```
Comment (VinceCarollo) [inline lib/game.rb:94]: Fixed! We don't need the not! 👍
