### PR TITLE
Bug fixes

### LINKED ISSUE #11: Valid Placement Bug
Things to fix

- [x] - valid_placement(['A1', 'A4', 'A3']) should return false NOT true

### PR DESCRIPTION
**Pull request by VinceCarollo**
What does this PR do?

- adds check for correct middle coordinate when checking valid_placement for cruiser ship
- fixes #11

### CODE REVIEW

File: lib/board.rb [hunk 1]
```diff
@@ -38,6 +38,10 @@ def valid_placement?(ship, coord)
     valid = false if coord.any? { |item| !valid_coordinate?(item) } ||
                      coord.any? { |item| !@cells[item].empty?}
 
+                     #check for odd middle coordinate
+    if coord.length == 3
```
Comment (JustinD85) [inline lib/board.rb:42]: Nice catch! That sneaky middle coordinate was causing a lot of pain!!

**Review by JustinD85 — APPROVED** [review]
